name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      upload_package: true

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: wheel-package
        path: dist/

    - name: Get wheel file
      id: wheel
      run: echo "path=$(ls dist/*.whl)" >> $GITHUB_OUTPUT

    - name: Upload package to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.wheel.outputs.path }}
        asset_name: wiremongo.whl
        asset_content_type: application/octet-stream

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}